
DEFINES+=PROJECT_CONF_H=\"../project-conf.h\"
PROJECT_SOURCEFILES += hid_leds.c
CONTIKI_PROJECT = light

TARGET = srf06-cc26xx
BOARD=sensortag/cc2650
CPU_FAMILY=cc26xx
CONTIKI_WITH_RIME=1


all: $(CONTIKI_PROJECT)

CONTIKI=../../../


include $(CONTIKI)/Makefile.include


