
DEFINES+=PROJECT_CONF_H=\"../project-conf.h\"
CONTIKI_PROJECT = rssi-test-send

TARGET = srf06-cc26xx
BOARD=sensortag/cc2650
CPU_FAMILY=cc26xx
CONTIKI_WITH_RIME=1


all: $(CONTIKI_PROJECT)

CONTIKI=../../../


include $(CONTIKI)/Makefile.include


